package group6.Swp391.Se1861.SchoolMedicalManagementSystem.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

/**
 * DTO for sending health check result notifications to parents
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class HealthCheckResultNotificationDTO {
    
    private Long campaignId;
    
    // If sending to specific students, include their IDs
    private List<String> studentIds;
    
    // For customized message template
    private String messageTemplate;
    
    // Whether to use auto-generated content based on results
    private boolean useAutoGeneratedContent;
    
    // Additional parameters for the message template
    private Map<String, Object> templateParams;
}
