name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'SWP_FRONTEND/**'
  pull_request:
    branches:
      - main
    paths:
      - 'SWP_FRONTEND/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'SWP_FRONTEND/frontend/package-lock.json'

      - name: Install dependencies
        working-directory: SWP_FRONTEND/frontend
        run: npm ci

      - name: Build project
        working-directory: SWP_FRONTEND/frontend
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCHOOLMEDICAL_SYSTEM }}
          projectId: schoolmedical-system
          channelId: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'live' || '' }}
          entryPoint: SWP_FRONTEND/frontend
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
